### ISSUE TITLE
"cannot convert undefined or null to object" error

### ISSUE THREAD

**Issue by neihcnim** [agracio/ts-react-json-table#6]
`     RowDataPacket {
       bname: null,
       lname: null,
       aname: null,
       areaid: null,
       status: null,
       name: 'Osram 1',
       panellabel: null,
       voltageid: null } ],
  pagination: { current: 0, perPage: 10, previous: null, next: 1 } }
TypeError: Cannot convert undefined or null to object
    at JsonTable.createColumns (/home/min/src/react2/node_modules/ts-react-json-table/src/grid.tsx:74:30)
    at JsonTable.render (/home/min/src/react2/node_modules/ts-react-json-table/src/grid.tsx:29:29)
    at processChild (/home/min/src/react2/node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (/home/min/src/react2/node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (/home/min/src/react2/node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (/home/min/src/react2/node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at Object.renderToStaticMarkup (/home/min/src/react2/node_modules/react-dom/cjs/react-dom-server.node.development.js:2740:25)
    at View.renderFile [as engine] (/home/min/src/react2/node_modules/express-react-views/index.js:68:32)
    at View.render (/home/min/src/react2/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/min/src/react2/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/min/src/react2/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/min/src/react2/node_modules/express/lib/response.js:1008:7)
    at /home/min/src/react2/app/standard.js:263:5
    at tryCatcher (/home/min/src/react2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/min/src/react2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/min/src/react2/node_modules/bluebird/js/release/promise.js:569:18)
`
Below is my code.
`<JsonTable rows={this.props.responsePayload} />)`

May I know what I can do to fix it? Thanks.

**Comment by neihcnim** [comment]
The object that I had passed in contained 2 objects instead of a array.
